version: '3'
services:
  db:
    image: mysql:8
    container_name: mysql_django_lms
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=django_lms
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - dbvol:/var/lib/mysql
    networks:
      - internal

  web:
    container_name: django_lms
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - "8000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - internal

  nginx:
    image: nginx
    container_name: nginx_django_lms
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - internal

  redis:
    image: redis

networks:
  internal:
    driver: bridge

volumes:
  dbvol: