# Generated by Django 4.2.6 on 2023-12-02 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_chapter_options_completedlesson_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedlesson',
            name='enrollment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.enrollment'),
        ),
    ]
